var formhtml= "                    <form class=\"mss-form\" name=\"\" method=\"post\" action=\"#\" id=\"\">"
+ "                        <div class=\"mss-form-item\">"
+ "                            <div class=\"mss-form-leftname\">文本项:</div>"
+ "                            <div class=\"mss-form-container\">"
+ "                                <div class=\"mss-form-container-box\">"
+ "                                    <div class=\"mss-form-text\">"
+ "                                        一个个文字文字<a class=\"mss-form-link\">验证</a>"
+ "                                    </div>"
+ "                                    <p class=\"mss-form-tip fn-cl-Red\"><i class=\"icon-remove\"></i>文本验证失败，请勿非法修改</p>"
+ "                                </div>"
+ "                            </div>"
+ "                        </div>"
+ "                        <div class=\"mss-form-item\">"
+ "                            <div class=\"mss-form-leftname\">输入框:</div>"
+ "                            <div class=\"mss-form-container\">"
+ "                                <div class=\"mss-form-container-box\">"
+ "                                    <div class=\"mss-form-box\">"
+ "                                        <input type=\"text\" class=\"mss-form-input-txt\">"
+ "                                    </div>"
+ "                                    <p class=\"mss-form-tip fn-cl-Green\"><i class=\"icon-warning-sign\"></i>异步验证成功</p>"
+ "                                </div>"
+ "                            </div>"
+ "                        </div>"
+ "                        <div class=\"mss-form-item\">"
+ "                            <div class=\"mss-form-leftname\">时间:</div>"
+ "                            <div class=\"mss-form-container\">"
+ "                                <div class=\"mss-form-container-box\">"
+ "                                    <div class=\"mss-form-box\">"
+ "                                        <div class=\"mss-form-input-lefticon\"><i class=\"mss-form-icon icon-table\"></i>"
+ "                                            <input type=\"text\" class=\"mss-form-input-txt mss-calendar\">"
+ "                                        </div>"
+ "                                        <div class=\"mss-form-split\"><em>-</em>"
+ "                                        </div>"
+ "                                        <div class=\"mss-form-input-righticon\">"
+ "                                            <input type=\"text\" class=\"mss-form-input-txt\"><i class=\"mss-form-icon icon-table\"></i>"
+ "                                        </div>"
+ "                                        <a class=\"mss-form-link\">验证</a>"
+ "                                    </div>"
+ "                                    <p class=\"mss-form-tip fn-cl-Orange\"><i class=\"icon-ok\"></i>选择时间过长，需要等待响应</p>"
+ "                                </div>"
+ "                            </div>"
+ "                        </div>"
+ "                        <div class=\"mss-form-item\">"
+ "                            <div class=\"mss-form-leftname\">邮箱:</div>"
+ "                            <div class=\"mss-form-container\">"
+ "                                <div class=\"mss-form-container-box\">"
+ "                                    <div class=\"mss-form-box\">"
+ "                                        <div class=\"mss-form-input-lefticon\">"
+ "                                            <input type=\"text\" class=\"mss-form-input-txt\" style=\"width:30px;\">"
+ "                                            <i class=\"mss-form-icon mss-form-boicon\">@</i>"
+ "                                            <input type=\"text\" class=\"mss-form-input-txt\" style=\"width:90px;\">"
+ "                                        </div>"
+ "                                    </div>"
+ "                                </div>"
+ "                            </div>"
+ "                        </div>"
+ "                        <div class=\"mss-form-item\">"
+ "                            <div class=\"mss-form-leftname\">RMB:</div>"
+ "                            <div class=\"mss-form-container\">"
+ "                                <div class=\"mss-form-container-box\">"
+ "                                    <div class=\"mss-form-box\">"
+ "                                        <div class=\"mss-form-input-lefticon\">"
+ "                                            <i class=\"mss-form-icon\">$</i>"
+ "                                            <input type=\"text\" class=\"mss-form-input-txt\">"
+ "                                            <i class=\"mss-form-icon mss-form-ricon\">.00</i>"
+ "                                        </div>"
+ "                                    </div>"
+ "                                </div>"
+ "                            </div>"
+ "                        </div>"
+ "                        <div class=\"mss-form-item\">"
+ "                            <div class=\"mss-form-leftname\">默认下拉:</div>"
+ "                            <div class=\"mss-form-container\">"
+ "                                <div class=\"mss-form-container-box\">"
+ "                                    <div class=\"mss-form-box\">"
+ "                                        <select name=\"\" class=\"mss-form-input-select\">"
+ "                                            <option>平台类型</option>"
+ "                                            <option>平台类型</option>"
+ "                                            <option>平台类型</option>"
+ "                                            <option>平台类型</option>"
+ "                                        </select>"
+ "                                        <input type=\"text\" class=\"mss-form-input-txt\">"
+ "                                    </div>"
+ "                                </div>"
+ "                            </div>"
+ "                        </div>"
+ "                        <div class=\"mss-form-item\">"
+ "                            <div class=\"mss-form-leftname\">模拟下拉:</div>"
+ "                            <div class=\"mss-form-container\">"
+ "                                <div class=\"mss-form-container-box\">"
+ "                                    <div class=\"mss-form-box\">"
+ "                                        <div class=\"mss-dropdown\">"
+ "                                            <div class=\"mss-dropdown-text\">"
+ "                                                <input class=\"mss-dropdown-input\" type=\"text\" value=\"设置代扣\" onfocus=\"this.blur()\" readonly/>"
+ "                                                <input class=\"mss-dropdown-val\" type=\"hidden\" value=\"1\" />"
+ "                                                <i class=\"icon-angle-down\" title=\"点击选择\"></i>"
+ "                                            </div>"
+ "                                            <ul class=\"mss-dropdown-list fn-show\">"
+ "                                                <li class=\"mss-dropdown-list-item fn-text-overflow\" data-value=\"2\">"
+ "                                                    <span>标为已缴</span>"
+ "                                                </li>"
+ "                                                <li class=\"mss-dropdown-list-item fn-text-overflow\" data-value=\"2\">"
+ "                                                    <span>标为已缴</span>"
+ "                                                </li>"
+ "                                            </ul>"
+ "                                        </div>"
+ "                                    </div>"
+ "                                </div>"
+ "                            </div>"
+ "                        </div>"
+ "                        <div class=\"mss-form-item\">"
+ "                            <div class=\"mss-form-leftname\">组合:</div>"
+ "                            <div class=\"mss-form-container\">"
+ "                                <div class=\"mss-form-container-box\">"
+ "                                    <div class=\"mss-form-box\">"
+ "                                        <select name=\"\" class=\"mss-form-input-select\">"
+ "                                            <option>平台类型</option>"
+ "                                            <option>平台类型</option>"
+ "                                            <option>平台类型</option>"
+ "                                            <option>平台类型</option>"
+ "                                        </select>"
+ "                                    </div>"
+ "                                </div>"
+ "                            </div>"
+ "                        </div>"
+ "                        <div class=\"mss-form-item\">"
+ "                            <div class=\"mss-form-leftname\">单选:</div>"
+ "                            <div class=\"mss-form-container\">"
+ "                                <div class=\"mss-form-container-box\">"
+ "                                    <div class=\"mss-form-check\">"
+ "                                        <label for=\"heckbox1\">"
+ "                                            <input type=\"radio\" name=\"heckbox3\" id=\"heckbox1\">无数据"
+ "                                        </label>"
+ "                                        <label for=\"heckbox2\">"
+ "                                            <input type=\"radio\" name=\"heckbox3\" id=\"heckbox2\">无数据"
+ "                                        </label>"
+ "                                        <label for=\"heckbox3\">"
+ "                                            <input type=\"radio\" name=\"heckbox3\" id=\"heckbox3\">无数据"
+ "                                        </label>"
+ "                                        <label for=\"heckbox4\">"
+ "                                            <input type=\"radio\" name=\"heckbox3\" id=\"heckbox4\">无数据"
+ "                                        </label>"
+ "                                    </div>"
+ "                                </div>"
+ "                            </div>"
+ "                        </div>"
+ "                        <div class=\"mss-form-item\">"
+ "                            <div class=\"mss-form-leftname\">多选:</div>"
+ "                            <div class=\"mss-form-container\">"
+ "                                <div class=\"mss-form-container-box\">"
+ "                                    <div class=\"mss-form-check\">"
+ "                                        <label for=\"checkbox1\">"
+ "                                            <input type=\"checkbox\" name=\"\" id=\"checkbox1\">无数据"
+ "                                        </label>"
+ "                                        <label for=\"checkbox2\">"
+ "                                            <input type=\"checkbox\" name=\"\" id=\"checkbox2\">无数据"
+ "                                        </label>"
+ "                                        <label for=\"checkbox3\">"
+ "                                            <input type=\"checkbox\" name=\"\" id=\"checkbox3\">无数据"
+ "                                        </label>"
+ "                                        <label for=\"checkbox4\">"
+ "                                            <input type=\"checkbox\" name=\"\" id=\"checkbox4\">无数据"
+ "                                        </label>"
+ "                                    </div>"
+ "                                </div>"
+ "                            </div>"
+ "                        </div>"
+ "                        <div class=\"mss-form-item\">"
+ "                            <div class=\"mss-form-leftname\">默认下拉:</div>"
+ "                            <div class=\"mss-form-container\">"
+ "                                <div class=\"mss-form-container-box\">"
+ "                                    <div class=\"mss-form-box\">"
+ "                                        <textarea class=\"mss-form-input-textarea\">一二三四五六七八九十</textarea>"
+ "                                    </div>"
+ "                                </div>"
+ "                            </div>"
+ "                        </div>"
+ "                        <div class=\"mss-form-item\">"
+ "                            <div class=\"mss-form-leftname\"></div>"
+ "                            <div class=\"mss-form-container\">"
+ "                                <div class=\"mss-form-container-box\">"
+ "                                    <div class=\"mss-form-check\">"
+ "                                        <label for=\"checkbox11\">"
+ "                                            <input type=\"checkbox\" name=\"\" id=\"checkbox11\">我已阅读并接受自主缴费服务协议"
+ "                                        </label>"
+ "                                    </div>"
+ "                                </div>"
+ "                            </div>"
+ "                        </div>"
+ "                        <div class=\"mss-form-item\">"
+ "                            <div class=\"mss-form-leftname\">验证码：</div>"
+ "                            <div class=\"mss-form-container\">"
+ "                                <div class=\"mss-form-container-box\">"
+ "                                    <div class=\"mss-form-box\">"
+ "                                        <input type=\"text\" class=\"mss-form-input-txt\">"
+ "                                        <img class=\"mss-form-imgcode\" align=\"absMiddle\" alt=\"请输入您看到的内容\" src=\"https://omeo.alipay.com/service/checkcode?sessionID=82012ab6b1f4ed9e675fb9092a25cb3b&amp;r=0.9321065918075809\" title=\"点击刷新图片校验码\" />"
+ "                                        <a class=\"mss-form-link\">看不清楚</a>"
+ "                                    </div>"
+ "                                </div>"
+ "                            </div>"
+ "                        </div>"
+ "                        <div class=\"mss-form-item\">"
+ "                            <div class=\"mss-form-leftname\"></div>"
+ "                            <div class=\"mss-form-container\">"
+ "                                <div class=\"mss-form-container-box\">"
+ "                                    <button class=\"mss-button fn-mr10 fn-bg-Blue\">确认</button>"
+ "                                    <button class=\"mss-button fn-mr10 \">取消</button>"
+ "                                </div>"
+ "                            </div>"
+ "                        </div>"
+ "                    </form>";